# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 08:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Department Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Faculty Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g. Religious..', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Interest Name')),
                ('description', models.TextField(blank=True, help_text='An optional description of the                                   interest, to aid in matching/searching', verbose_name='Description')),
                ('related_interests', models.ManyToManyField(related_name='_interest_related_interests_+', to='kaldb.Interest', verbose_name='Related                                               Interests')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Research Assistant, Lecturer,                            Professor...', max_length=120, verbose_name='Job Position')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'in Roman Sculpture'", max_length=120, verbose_name='Job Role')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Module Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('assessment', models.TextField(blank=True, verbose_name='Assessments')),
                ('teaching_pattern', models.TextField(blank=True, verbose_name='Teaching                                        Pattern')),
                ('url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Module URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Module Level')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutReachCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='City Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Out reach cities',
            },
        ),
        migrations.CreateModel(
            name='OutReachCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Not                            needed if City is known, country will be                            automatically populated', max_length=120, verbose_name='City Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Out reeach countries',
            },
        ),
        migrations.CreateModel(
            name='OutReachEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Outreach Title')),
                ('description', models.TextField(blank=True, help_text='An optional description of the                                   outreach, to aid in matching/searching', verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutReachFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Once, Cccasionally, Often...', max_length=120, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Out reach frequencies',
            },
        ),
        migrations.CreateModel(
            name='OutReachLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=32140)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCity', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCountry', verbose_name='OR Country')),
            ],
        ),
        migrations.CreateModel(
            name='OutReachMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Radio, TV, Talk...', max_length=120, verbose_name='Medium')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='Middle Name(s)')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('email', models.CharField(blank=True, max_length=120, verbose_name='E-Mail Address')),
                ('phone', models.CharField(blank=True, help_text='For KCL staff a 4 digit                             extension is sufficient', max_length=120, verbose_name='Telephone Number')),
                ('can_email', models.BooleanField(default=True, help_text='Is this person willing to be                                    contacted by e-mail?', verbose_name='Can E-mail?')),
                ('can_phone', models.BooleanField(default=True, help_text='Is this person willing to be                                    contacted by phone?', verbose_name='Can Phone?')),
                ('pure_url', models.CharField(blank=True, help_text='Link to pure profile', max_length=512, verbose_name='Pure URL')),
                ('profile_url', models.CharField(blank=True, help_text='Link to personal website                                   within KCL (e.g. departmental profile)', max_length=512, verbose_name='KCL Profile URL')),
                ('other_url', models.CharField(blank=True, help_text='Link                                 to personal website outside of KCL', max_length=512, verbose_name='Non-KCL Profile URL')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.Department')),
                ('institutions', models.ManyToManyField(blank=True, to='kaldb.Institution', verbose_name='Institutions')),
                ('locations', models.ManyToManyField(blank=True, to='kaldb.OutReachLocation', verbose_name='Locations')),
                ('position', models.ForeignKey(blank=True, help_text='e.g. Lecturer, Professor...', null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.JobPosition', verbose_name='Job Position')),
                ('research_interests', models.ManyToManyField(blank=True, related_name='research_int', to='kaldb.Interest', verbose_name='Research                                                Interests')),
                ('role', models.ForeignKey(blank=True, help_text="e.g. 'in Roman Sculpture'", null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.JobRole')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brief name given to the                            specialism', max_length=1024, verbose_name='London Specialism')),
                ('description', models.TextField(blank=True, help_text='An optional description of                                   the specialism', verbose_name='Description')),
                ('london_related', models.BooleanField(default=True, help_text='Is this                                         specialism related to London?', verbose_name='London Related?')),
                ('kcl_related', models.BooleanField(default=True, help_text='Was this                                      research performed at KCL?', verbose_name='KCL Related?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Theme Name')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Description')),
                ('modules', models.ManyToManyField(blank=True, to='kaldb.Module', verbose_name='Related                                   Modules')),
                ('roles', models.ManyToManyField(blank=True, to='kaldb.JobRole', verbose_name='Related                                   Job Roles')),
                ('specialisms', models.ManyToManyField(blank=True, to='kaldb.Specialism', verbose_name='Related                                   London Specialisms')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mr, Ms, Dr...', max_length=120, verbose_name='Title')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='researcher',
            name='specialisms',
            field=models.ManyToManyField(blank=True, to='kaldb.Specialism', verbose_name='Specialisms'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='teaching_interests',
            field=models.ManyToManyField(blank=True, related_name='teaching_int', to='kaldb.Interest', verbose_name='Teaching                                                Interests'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.Title', verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='outreachevent',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachFrequency', verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='outreachevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachLocation', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='outreachevent',
            name='medium',
            field=models.ForeignKey(blank=True, help_text='Medium (e.g. Radio, TV, Talk...)', null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachMedium', verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='outreachevent',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.Researcher'),
        ),
        migrations.AddField(
            model_name='outreachcity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCountry'),
        ),
        migrations.AddField(
            model_name='module',
            name='convenors',
            field=models.ManyToManyField(blank=True, to='kaldb.Researcher', verbose_name='Module Convenors'),
        ),
        migrations.AddField(
            model_name='module',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.Department'),
        ),
        migrations.AddField(
            model_name='module',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='kaldb.Institution'),
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.ManyToManyField(blank=True, to='kaldb.ModuleLevel', verbose_name='Module Level'),
        ),
        migrations.AddField(
            model_name='module',
            name='locations',
            field=models.ManyToManyField(blank=True, to='kaldb.OutReachLocation'),
        ),
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.InstitutionCategory'),
        ),
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.ManyToManyField(blank=True, to='kaldb.OutReachLocation'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.Faculty', verbose_name='Faculty'),
        ),
    ]
