# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Faculty Name')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Interest Name')),
                ('description', models.TextField(blank=True, help_text='An optional description of the interest, to aid in matching/searching', verbose_name='Description')),
                ('related_interests', models.ManyToManyField(related_name='_interest_related_interests_+', to='kaldb.Interest', verbose_name='Related Interests')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Research Assistant, Lecturer, Professor...', max_length=120, verbose_name='Job Position')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'in Roman Sculpture'", max_length=120, verbose_name='Job Role')),
            ],
        ),
        migrations.CreateModel(
            name='OutReachCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='OutReachCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='OutReachFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Once, Cccasionally, Often...', max_length=120, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='OutReachLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_lat', models.CharField(blank=True, help_text='If known', max_length=120, verbose_name='Lat.')),
                ('coord_long', models.CharField(blank=True, help_text='If known', max_length=120, verbose_name='Long.')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCity', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCountry')),
            ],
        ),
        migrations.CreateModel(
            name='OutReachMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Radio, TV, Talk...', max_length=120, verbose_name='Medium')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Lecturer, Research Assistant, Professor...', max_length=120, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='Middle Name(s)')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('role', models.CharField(help_text="e.g. 'in Roman Sculpture'", max_length=120, verbose_name='Job Role')),
                ('email', models.CharField(blank=True, max_length=120, verbose_name='E-Mail Address')),
                ('phone', models.CharField(blank=True, help_text='For KCL staff a 4 digit extension is sufficient', max_length=120, verbose_name='Telephone Number')),
                ('can_email', models.BooleanField(default=True, help_text='Is this person willing to be contacted by e-mail?', verbose_name='Can E-mail?')),
                ('can_phone', models.BooleanField(default=True, help_text='Is this person willing to be contacted by phone?', verbose_name='Can Phone?')),
                ('pure_url', models.CharField(blank=True, help_text='Link to pure profile', max_length=512, verbose_name='Pure URL')),
                ('profile_url', models.CharField(blank=True, help_text='Link to personal website within KCL (e.g. departmental profile)', max_length=512, verbose_name='KCL Profile URL')),
                ('other_url', models.CharField(blank=True, help_text='Link to personal website outside of KCL', max_length=512, verbose_name='Non-KCL Profile URL')),
                ('position', models.ForeignKey(help_text='e.g. Lecturer, Professor...', on_delete=django.db.models.deletion.CASCADE, to='kaldb.JobPosition', verbose_name='Job Position')),
                ('research_interests', models.ManyToManyField(related_name='research_interests', to='kaldb.Interest', verbose_name='Research Interests')),
                ('teaching_interests', models.ManyToManyField(related_name='teaching_interests', to='kaldb.Interest', verbose_name='Teaching Interests')),
            ],
        ),
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brief name given to the specialism', max_length=1024, verbose_name='Specialism Name')),
                ('description', models.TextField(blank=True, help_text='An optional description of the specialism', verbose_name='Description')),
                ('london_related', models.BooleanField(default=True, help_text='Is this specialism related to London?', verbose_name='London Related?')),
                ('kcl_related', models.BooleanField(default=True, help_text='Was this research performed at KCL?', verbose_name='KCL Related?')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mr, Ms, Dr...', max_length=120, verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='researcher',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.Title', verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='outreachcity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCountry'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.Faculty', verbose_name='Faculty'),
        ),
    ]
