# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutReachEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Outreach Title')),
                ('description', models.TextField(blank=True, help_text='An optional description of the                                    outreach, to aid in matching/searching', verbose_name='Description')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachFrequency', verbose_name='Frequency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachLocation', verbose_name='Location')),
                ('medium', models.ForeignKey(help_text='Medium (e.g. Radio, TV, Talk...)', on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachMedium', verbose_name='Medium')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.Researcher')),
            ],
        ),
        migrations.AlterField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True, help_text='An optional description of the                                    interest, to aid in matching/searching', verbose_name='Description'),
        ),
    ]
