# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Research Grant', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Project Title')),
                ('date_d', models.IntegerField(verbose_name='Day')),
                ('date_m', models.IntegerField(verbose_name='Month')),
                ('date_y', models.IntegerField(verbose_name='Year')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Value of Collaboration')),
                ('partner_is_lead', models.BooleanField(default=False, verbose_name='Was the partner lead?')),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.AwardType', verbose_name='Award Type')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachLocation')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Higher Education..', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. award', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='institutioncategory',
            name='description',
            field=models.CharField(help_text='e.g. Religious..', max_length=128),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='partner_sector',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.InstitutionSector'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='partner_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.InstitutionCategory'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.Researcher'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='stage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.StageType', verbose_name='Stage Type'),
        ),
    ]
