# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0002_auto_20170314_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.Department'),
        ),
    ]
