# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0002_auto_20170613_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='location',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='partner_sector',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='partner_type',
        ),
        migrations.AddField(
            model_name='institution',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.InstitutionSector'),
        ),
        migrations.AlterField(
            model_name='outreachcity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCountry'),
        ),
    ]
