# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0003_researcher_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AlterField(
            model_name='researcher',
            name='role',
            field=models.ForeignKey(help_text="e.g. 'in Roman Sculpture'", on_delete=django.db.models.deletion.CASCADE, to='kaldb.JobRole'),
        ),
    ]
