# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0003_auto_20170613_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='external',
            field=models.BooleanField(default=False, verbose_name='External To Kings'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='award_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.AwardType', verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='date_d',
            field=models.IntegerField(blank=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='date_m',
            field=models.IntegerField(blank=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='stage_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.StageType', verbose_name='Stage Type'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Value of Collaboration'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.Department'),
        ),
    ]
