# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 10:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0004_auto_20170613_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachlocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3214),
        ),
    ]
