# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0005_auto_20170314_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(help_text='Research Assistant, Lecturer,                            Professor...', max_length=120, verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='outreachevent',
            name='description',
            field=models.TextField(blank=True, help_text='An optional description of the                                   outreach, to aid in matching/searching', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='outreachmedium',
            name='name',
            field=models.CharField(help_text='Radio, TV, Talk...', max_length=120, verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='specialism',
            name='description',
            field=models.TextField(blank=True, help_text='An optional description of                                   the specialism', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='specialism',
            name='kcl_related',
            field=models.BooleanField(default=True, help_text='Was this                                      research performed at KCL?', verbose_name='KCL Related?'),
        ),
        migrations.AlterField(
            model_name='specialism',
            name='london_related',
            field=models.BooleanField(default=True, help_text='Is this                                         specialism related to London?', verbose_name='London Related?'),
        ),
        migrations.AlterField(
            model_name='specialism',
            name='name',
            field=models.CharField(help_text='Brief name given to the                            specialism', max_length=1024, verbose_name='Specialism Name'),
        ),
    ]
