# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0006_auto_20170314_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='specialism',
            field=models.ManyToManyField(to='kaldb.Specialism', verbose_name='Specialisms'),
        ),
        migrations.AlterField(
            model_name='outreachcountry',
            name='name',
            field=models.CharField(blank=True, help_text='Not                            needed if City is known, country will be                            automatically populated', max_length=120, verbose_name='City Name'),
        ),
    ]
