# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0006_auto_20170613_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionsector',
            old_name='name',
            new_name='description',
        ),
    ]
