# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0007_auto_20170314_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachlocation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachCountry', verbose_name='OR Country'),
        ),
    ]
