# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0007_auto_20170613_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachlocation',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
