# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0008_auto_20170613_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.Faculty', verbose_name='Faculty/School'),
        ),
    ]
