# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0008_auto_20170314_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.Title', verbose_name='Title'),
        ),
    ]
