# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0010_auto_20170403_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='role',
            field=models.ForeignKey(blank=True, help_text="e.g. 'in Roman Sculpture'", null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.JobRole'),
        ),
    ]
