# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0010_auto_20170613_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='accholder',
            field=models.ManyToManyField(related_name='accholder', to='kaldb.Researcher'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='coinv',
            field=models.ManyToManyField(related_name='coinv', to='kaldb.Researcher'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='extcoapp',
            field=models.ManyToManyField(related_name='extcoapp', to='kaldb.Researcher'),
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='pi',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='pi',
            field=models.ManyToManyField(related_name='pi', to='kaldb.Researcher'),
        ),
    ]
