# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0011_auto_20170403_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachevent',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachFrequency', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='outreachevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachLocation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='outreachevent',
            name='medium',
            field=models.ForeignKey(blank=True, help_text='Medium (e.g. Radio, TV, Talk...)', null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.OutReachMedium', verbose_name='Medium'),
        ),
    ]
