# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0012_auto_20170403_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachevent',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Outreach Title'),
        ),
    ]
