# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0012_theme_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
