# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0013_auto_20170403_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='jobrole',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outreachcity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outreachcountry',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outreachevent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outreachfrequency',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outreachmedium',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
        migrations.AlterModelOptions(
            name='specialism',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
    ]
