# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0013_theme_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
