# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0014_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
