# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0014_auto_20170403_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='position',
            field=models.ForeignKey(blank=True, help_text='e.g. Lecturer, Professor...', null=True, on_delete=django.db.models.deletion.CASCADE, to='kaldb.JobPosition', verbose_name='Job Position'),
        ),
    ]
