# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0015_auto_20170403_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='research_interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='research_int', to='kaldb.Interest', verbose_name='Research                                                Interests'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='specialism',
            field=models.ManyToManyField(blank=True, null=True, to='kaldb.Specialism', verbose_name='Specialisms'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='teaching_interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='teaching_int', to='kaldb.Interest', verbose_name='Teaching                                                Interests'),
        ),
    ]
