# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0015_auto_20170622_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='can_email',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='can_phone',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='phone',
        ),
    ]
