# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0016_auto_20170403_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='specialism',
            new_name='specialisms',
        ),
    ]
