# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0016_removed_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='researcher',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
