# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0017_add_image_fields_to_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='researchers'),
        ),
    ]
