# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 14:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0019_researcher_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
