# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaldb', '0023_auto_20170420_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='themes',
            field=models.ManyToManyField(to='kaldb.Theme'),
        ),
    ]
